/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var maven_pb = require('./maven_pb.js');
goog.object.extend(proto, maven_pb);
var gitlab_pb = require('./gitlab_pb.js');
goog.object.extend(proto, gitlab_pb);
goog.exportSymbol('proto.maven.DeploySource', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.maven.DeploySource = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.maven.DeploySource.oneofGroups_);
};
goog.inherits(proto.maven.DeploySource, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.maven.DeploySource.displayName = 'proto.maven.DeploySource';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.maven.DeploySource.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.maven.DeploySource.SourceCase = {
  SOURCE_NOT_SET: 0,
  MAVEN: 1,
  GITLAB: 2
};

/**
 * @return {proto.maven.DeploySource.SourceCase}
 */
proto.maven.DeploySource.prototype.getSourceCase = function() {
  return /** @type {proto.maven.DeploySource.SourceCase} */(jspb.Message.computeOneofCase(this, proto.maven.DeploySource.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.maven.DeploySource.prototype.toObject = function(opt_includeInstance) {
  return proto.maven.DeploySource.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.maven.DeploySource} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.maven.DeploySource.toObject = function(includeInstance, msg) {
  var f, obj = {
    maven: (f = msg.getMaven()) && maven_pb.MavenDeploySource.toObject(includeInstance, f),
    gitlab: (f = msg.getGitlab()) && gitlab_pb.GitlabBuildSource.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.maven.DeploySource}
 */
proto.maven.DeploySource.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.maven.DeploySource;
  return proto.maven.DeploySource.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.maven.DeploySource} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.maven.DeploySource}
 */
proto.maven.DeploySource.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new maven_pb.MavenDeploySource;
      reader.readMessage(value,maven_pb.MavenDeploySource.deserializeBinaryFromReader);
      msg.setMaven(value);
      break;
    case 2:
      var value = new gitlab_pb.GitlabBuildSource;
      reader.readMessage(value,gitlab_pb.GitlabBuildSource.deserializeBinaryFromReader);
      msg.setGitlab(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.maven.DeploySource.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.maven.DeploySource.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.maven.DeploySource} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.maven.DeploySource.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMaven();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      maven_pb.MavenDeploySource.serializeBinaryToWriter
    );
  }
  f = message.getGitlab();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      gitlab_pb.GitlabBuildSource.serializeBinaryToWriter
    );
  }
};


/**
 * optional MavenDeploySource maven = 1;
 * @return {?proto.maven.MavenDeploySource}
 */
proto.maven.DeploySource.prototype.getMaven = function() {
  return /** @type{?proto.maven.MavenDeploySource} */ (
    jspb.Message.getWrapperField(this, maven_pb.MavenDeploySource, 1));
};


/** @param {?proto.maven.MavenDeploySource|undefined} value */
proto.maven.DeploySource.prototype.setMaven = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.maven.DeploySource.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.maven.DeploySource.prototype.clearMaven = function() {
  this.setMaven(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.maven.DeploySource.prototype.hasMaven = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional GitlabBuildSource gitlab = 2;
 * @return {?proto.maven.GitlabBuildSource}
 */
proto.maven.DeploySource.prototype.getGitlab = function() {
  return /** @type{?proto.maven.GitlabBuildSource} */ (
    jspb.Message.getWrapperField(this, gitlab_pb.GitlabBuildSource, 2));
};


/** @param {?proto.maven.GitlabBuildSource|undefined} value */
proto.maven.DeploySource.prototype.setGitlab = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.maven.DeploySource.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 */
proto.maven.DeploySource.prototype.clearGitlab = function() {
  this.setGitlab(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.maven.DeploySource.prototype.hasGitlab = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.maven);
